
/**************************************************************
 *	
 *	collectingCoins, 8 bit, 11025Hz,
 *	1 channel, 4884 bytes/channel
 *	Total Size: 1 * 4884 + 4 (header) = 4928 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\anumb\Desktop\Spring'19\CS2261\milestones\M4\M04\collectingCoins.wav
 *	Time-stamp: Wed Apr 17 22:19:58 2019
 *	
 **************************************************************/

#ifndef __COLLECTINGCOINSH__
#define __COLLECTINGCOINSH__

#define COLLECTINGCOINSFREQ 11025
#define COLLECTINGCOINSLEN 4884

extern const unsigned char collectingCoins[4884];

#endif /* __COLLECTINGCOINSH__ */
