
/**************************************************************
 *	
 *	crashSound, 8 bit, 22050Hz,
 *	1 channel, 57605 bytes/channel
 *	Total Size: 1 * 57605 + 4 (header) = 57649 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\anumb\Desktop\Spring'19\CS2261\milestones\M4\M04\crashSound.wav
 *	Time-stamp: Thu Apr 18 14:37:32 2019
 *	
 **************************************************************/

#ifndef __CRASHSOUNDH__
#define __CRASHSOUNDH__

#define CRASHSOUNDFREQ 22050
#define CRASHSOUNDLEN 57000

extern const unsigned char crashSound[57605];

#endif /* __CRASHSOUNDH__ */
