
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 1776009 bytes/channel
 *	Total Size: 1 * 1776009 + 4 (header) = 1776053 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\anumb\Desktop\Spring'19\CS2261\milestones\M4\M04\GameSong.wav
 *	Time-stamp: Thu Apr 18 21:24:14 2019
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 1776009

extern const unsigned char GameSong[1776009];

#endif /* __GAMESONGH__ */
