
/**************************************************************
 *	
 *	instructSong, 8 bit, 11025Hz,
 *	1 channel, 594835 bytes/channel
 *	Total Size: 1 * 594835 + 4 (header) = 594879 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\anumb\Desktop\Spring'19\CS2261\milestones\M4\M04\instructSong.wav
 *	Time-stamp: Thu Apr 18 14:43:22 2019
 *	
 **************************************************************/

#ifndef __INSTRUCTSONGH__
#define __INSTRUCTSONGH__

#define INSTRUCTSONGFREQ 11025
#define INSTRUCTSONGLEN 594835

extern const unsigned char instructSong[594835];

#endif /* __INSTRUCTSONGH__ */
