
/**************************************************************
 *	
 *	loseSound, 8 bit, 11025Hz,
 *	1 channel, 153595 bytes/channel
 *	Total Size: 1 * 153595 + 4 (header) = 153639 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\anumb\Desktop\Spring'19\CS2261\milestones\M4\M04\loseSound.wav
 *	Time-stamp: Wed Apr 17 23:52:55 2019
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 11025
#define LOSESOUNDLEN 153595

extern const unsigned char loseSound[153595];

#endif /* __LOSESOUNDH__ */
