
/**************************************************************
 *	
 *	mainSong, 8 bit, 11025Hz,
 *	1 channel, 2071552 bytes/channel
 *	Total Size: 1 * 2071552 + 4 (header) = 2071596 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\anumb\Desktop\Spring'19\CS2261\milestones\M4\M04\mainSong.wav
 *	Time-stamp: Tue Apr 16 13:05:31 2019
 *	
 **************************************************************/

#ifndef __MAINSONGH__
#define __MAINSONGH__

#define MAINSONGFREQ 11025
#define MAINSONGLEN 2071552

extern const unsigned char mainSong[2071552];

#endif /* __MAINSONGH__ */
